const JWT_SECRET_KEY = 'JWT_SECRET'
const HASH_ROUND = 'HASH_ROUND'
const BASE_URL = 'BASE_URL'
const POSTGRES_HOST = 'POSTGRES_HOST'
const POSTGRES_PORT = 'POSTGRES_PORT'
const POSTGRES_USERNAME = 'POSTGRES_USERNAME'
const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD'
const POSTGRES_DATABASE = 'POSTGRES_DATABASE'

export const envKeys = {
  JWT_SECRET_KEY,
  HASH_ROUND,
  BASE_URL,
  POSTGRES_HOST,
  POSTGRES_PORT,
  POSTGRES_USERNAME,
  POSTGRES_PASSWORD,
  POSTGRES_DATABASE
} as const
